POST http://localhost:8080/api/register

Content-Type: application/json
{
  "name": "Tahmid",
  "age": 9,
  "email": "tm.ahad.bd@gmail.com",
  "accountName": "Tahmid",
  "password": "@054004$054003#054005"
}

POST http://localhost:8080/api/register

@token = "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c"

Content-Type: application/json
Authorization: Bearer @token
{
  "name": "Tahmid",
  "age": 9,
  "email": "tm.ahad.bd@gmail.com",
  "accountName": "Tahmid",
  "password": "@054004$054003#054005"
}
